# Pandas Method Task: Bank Customer Churn Dataset

In [ ]:
#csv:load the dataset

In [12]:
df=pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")

In [13]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [20]:
#1.Load the dataset using the appropriate Pandas method and store it in a
#variable named df.
sets=(1,2,3,5)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [21]:
#2Display the first 8 rows of the dataset.

df.head(8)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1

In [22]:
#3.Display the last 12 rows of the dataset.

df.tail(12)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [25]:
#4.Show 10 random rows from the dataset.

df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
277,57,1,1,124,261,0,1,141,0,0.3,2,0,3,0

In [29]:
#5. Find the shape of the dataset.
#o How many rows are there?
#o How many columns are there?
df.shape

(303, 14)

In [30]:
df.info

<bound method DataFrame.info of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [31]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [32]:
#6.Display complete information about the dataset using one method.
#o Number of non-null values
#o Data types
#o Memory usage

df.info

<bound method DataFrame.info of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [33]:
#7.Print the names of all columns in the dataset.

df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [34]:
#8.Find the data type of every column.

print(df.dtypes)

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [36]:
#9. Check for missing values in every column using:
#o isnull().sum()
#o isna().sum()

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [37]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [3]:
#10.Select only one column:
#o CreditScore

creditScore=(["CreditScore"])

In [6]:
#11.Select the following multiple columns:
#o CustomerId
#o Surname
#o Balance
#o Exited

[["CustomerId", "Surname", "Balance", "Exited"]]

[['CustomerId', 'Surname', 'Balance', 'Exited']]

In [6]:
#12.Display only numeric columns using select_dtypes()

import pandas as pd
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")

# Select only numeric columns
numeric_df = df.select_dtypes(include='number')

# Display first 5 rows
numeric_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [56]:
#13.Generate the statistical summary of all numeric columns using describe().

df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [60]:
#14.Check for duplicate rows in the dataset.
#o How many duplicate rows exist?
#o Remove all duplicate rows.

df.duplicated().sum()

np.int64(1)

In [63]:
df.drop_duplicates()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [64]:
#15.Count the number of customers in each class of the Exited column using
#value_counts().

df.value_counts()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
29   1    1   130       204   0    0        202      0      0.0      2      0   2     1         1
59   1    2   150       212   1    1        157      0      1.6      2      0   2     1         1
          1   140       221   0    1        164      1      0.0      2      0   2     1         1
          0   170       326   0    0        140      1      3.4      0      0   3     0         1
              164       176   1    0        90       0      1.0      1      2   1     0         1
                                                                                               ..
51   1    0   140       299   0    1        173      1      1.6      2      0   3     0         1
                        298   0    1        122      1      4.2      1      3   3     0         1
                        261   0    0        186      1      0.0      2      0   2     1         1
     0    2   140       308   0    0        142      0      1.5      2      1   2     1         1
77   1    0   125       304   0    0        162      1      0.0      2      3   2     0         1
Name: count, Length: 302, dtype: int64

# Operators + Loops (1-5)

In [65]:
#1.Take two numbers from user. Perform all arithmetic operations and also check
#which number is greater using comparison operators.


# Take two numbers from the user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# Arithmetic Operations
print("Addition =", num1 + num2)
print("Subtraction =", num1 - num2)
print("Multiplication =", num1 * num2)
print("Division =", num1 / num2)
print("Modulus =", num1 % num2)
print("Floor Division =", num1 // num2)
print("Exponent =", num1 ** num2)

# Comparison Operators
print("num1 > num2 :", num1 > num2)
print("num1 < num2 :", num1 < num2)
print("num1 == num2 :", num1 == num2)
print("num1 != num2 :", num1 != num2)
print("num1 >= num2 :", num1 >= num2)
print("num1 <= num2 :", num1 <= num2)

# Check which number is greater
if num1 > num2:
    print(num1, "is greater")
elif num2 > num1:
    print(num2, "is greater")
else:
    print("Both numbers are equal")

Enter first number:  7
Enter second number:  9

Addition = 16
Subtraction = -2
Multiplication = 63
Division = 0.7777777777777778
Modulus = 7
Floor Division = 0
Exponent = 40353607
num1 > num2 : False
num1 < num2 : True
num1 == num2 : False
num1 != num2 : True
num1 >= num2 : False
num1 <= num2 : True
9 is greater

In [66]:
#2.Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
#completely when number 40 is reached using break.

# Print numbers from 1 to 50

for i in range(1, 51):
    if i == 40:
        break          # Stop the loop when number is 40

    if i % 5 == 0:
        continue       # Skip multiples of 5

    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

In [68]:
#3.Take numbers from user until they enter negative number. Calculate sum and
#average using while loop.

# Initialize variables
total = 0
count = 0

while True:
    num = int(input("Enter a number: "))

    if num < 0:
        break

    total = total + num
    count = count + 1

# Calculate average
if count > 0:
    average = total / count
    print("Sum =", total)
    print("Average =", average)
else:
    print("No positive numbers entered.")

Enter a number:  10
Enter a number:  20
Enter a number:  30
Enter a number:  -1

Sum = 60
Average = 20.0

In [74]:
#4.Print the following pattern using nested loops:
#*****
#****
#***
#**
#*

for i in range(5, 0, -1):
    for j in range(i):
        print("*", end="")
    print()

*****
****
***
**
*

In [2]:
#5.Find the factorial of a number using for loop and also using while loop.

num = int(input("Enter a number: "))
fact = 1

for i in range(1, num + 1):
    fact = fact * i
print("Factorial =", fact)

Enter a number:  8

Factorial = 40320

# Data Types & Methods (6-9)

In [3]:
#6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
#spaces with -, and check if it starts with “Hello”.
text = input("Enter a string: ")

# Convert to uppercase
print("Uppercase:", text.upper())

# Count occurrences of 'a'
print("Count of 'a':", text.count('a'))

# Replace spaces with '-'
print("After replacing spaces:", text.replace(" ", "-"))

# Check if it starts with "Hello"
if text.startswith("Hello"):
    print("The string starts with 'Hello'")
else:
    print("The string does not start with 'Hello'")

Enter a string:  i am vaishu

Uppercase: I AM VAISHU
Count of 'a': 2
After replacing spaces: i-am-vaishu
The string does not start with 'Hello'

In [7]:
#7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
#and reverse.

# Create a list of 6 numbers
numbers = [10, 5, 30, 15, 25, 20]

print("Original List:", numbers)

# Append
numbers.append(40)
print("After append:", numbers)

# Insert
numbers.insert(2, 12)
print("After insert:", numbers)

# Remove
numbers.remove(15)
print("After remove:", numbers)

# Pop
numbers.pop()
print("After pop:", numbers)

# Sort in descending order
numbers.sort(reverse=True)
print("After descending sort:", numbers)

# Reverse
numbers.reverse()
print("After reverse:", numbers)

Original List: [10, 5, 30, 15, 25, 20]
After append: [10, 5, 30, 15, 25, 20, 40]
After insert: [10, 5, 12, 30, 15, 25, 20, 40]
After remove: [10, 5, 12, 30, 25, 20, 40]
After pop: [10, 5, 12, 30, 25, 20]
After descending sort: [30, 25, 20, 12, 10, 5]
After reverse: [5, 10, 12, 20, 25, 30]

In [9]:
#8. Create a dictionary of 4 students (name:marks). Print only those students who
#scored more than 80 using items().

# Dictionary of 4 students
students = {
    "vaishu": 85,
    "aarohi": 78,
    "shruti": 92,
    "Priya": 81
}

print("Students who scored more than 80:")

for name, marks in students.items():
    if marks > 80:
        print(name, ":", marks)

Students who scored more than 80:
vaishu : 85
shruti : 92
Priya : 81

In [11]:
#9.Create two sets and perform union, intersection, difference. Also add and discard
#elements.
# Create two sets
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

print("Set1:", set1)
print("Set2:", set2)

# Union
print("Union:", set1.union(set2))

# Intersection
print("Intersection:", set1.intersection(set2))

# Difference
print("Difference (set1 - set2):", set1.difference(set2))

# Add an element
set1.add(7)
print("After add:", set1)

# Discard an element
set1.discard(2)
print("After discard:", set1)

Set1: {1, 2, 3, 4}
Set2: {3, 4, 5, 6}
Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4}
Difference (set1 - set2): {1, 2}
After add: {1, 2, 3, 4, 7}
After discard: {1, 3, 4, 7}

# OOP + Encapsulation (10-14)

In [12]:
#10.Create a class Student with private attribute __marks. Add getter and setter with
#validation (0–100).

class Student:
    def __init__(self):
        self.__marks = 0   # Private attribute

    # Getter
    def get_marks(self):
        return self.__marks

    # Setter with validation
    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks = marks
        else:
            print("Invalid marks! Enter marks between 0 and 100.")
# Create object
s = Student()

# Set marks
s.set_marks(85)

# Get marks
print("Marks:", s.get_marks())

# Invalid marks
s.set_marks(120)

Marks: 85
Invalid marks! Enter marks between 0 and 100.

In [13]:
#11.Create class BankAccount with private __balance. Add deposit and withdraw
#methods. Raise custom exception if balance becomes negative.

# Custom Exception
class InsufficientBalanceError(Exception):
    pass

# BankAccount Class
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance   # Private attribute

    def deposit(self, amount):
        self.__balance += amount
        print("Deposited:", amount)

    def withdraw(self, amount):
        if self.__balance - amount < 0:
            raise InsufficientBalanceError("Insufficient Balance!")
        self.__balance -= amount
        print("Withdrawn:", amount)

    def get_balance(self):
        return self.__balance
# Create object
account = BankAccount(5000)

try:
    account.deposit(1000)
    account.withdraw(2000)
    print("Balance:", account.get_balance())

    account.withdraw(5000)   # Raises exception

except InsufficientBalanceError as e:
    print(e)

Deposited: 1000
Withdrawn: 2000
Balance: 4000
Insufficient Balance!

In [14]:
#12.Create class Employee with class attribute company_name. Show that it is
#shared by all objects. Also update the class attribute.

# Employee Class
class Employee:
    company_name = "ABC Pvt Ltd"   # Class attribute

    def __init__(self, name):
        self.name = name

# Create objects
emp1 = Employee("Rahul")
emp2 = Employee("Priya")

# Display company name
print(emp1.name, "works at", emp1.company_name)
print(emp2.name, "works at", emp2.company_name)

# Update class attribute
Employee.company_name = "XYZ Technologies"

print("\nAfter updating company name:")

print(emp1.name, "works at", emp1.company_name)
print(emp2.name, "works at", emp2.company_name)

Rahul works at ABC Pvt Ltd
Priya works at ABC Pvt Ltd

After updating company name:
Rahul works at XYZ Technologies
Priya works at XYZ Technologies

In [15]:
#13.Create class Product with private __price. Add getter and setter. Setter should
#not allow price less than 100.

# Product Class
class Product:
    def __init__(self):
        self.__price = 100   # Private attribute

    # Getter
    def get_price(self):
        return self.__price

    # Setter with validation
    def set_price(self, price):
        if price >= 100:
            self.__price = price
        else:
            print("Price should not be less than 100.")

# Create object
p = Product()

# Set valid price
p.set_price(500)
print("Price:", p.get_price())

# Set invalid price
p.set_price(50)
print("Price:", p.get_price())

Price: 500
Price should not be less than 100.
Price: 500

In [16]:
#14.Create class Rectangle with private length and width. Add method to calculate
#area and perimeter.

# Rectangle Class
class Rectangle:
    def __init__(self, length, width):
        self.__length = length    # Private attribute
        self.__width = width      # Private attribute

    # Method to calculate area
    def area(self):
        return self.__length * self.__width

    # Method to calculate perimeter
    def perimeter(self):
        return 2 * (self.__length + self.__width)

# Create object
r = Rectangle(10, 5)

# Display results
print("Area:", r.area())
print("Perimeter:", r.perimeter())

Area: 50
Perimeter: 30

# Inheritance + Abstraction + super() (15-19)

In [17]:
#15.Create single level inheritance: Person → Student. Use super() in constructor.

# Parent Class
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

# Child Class
class Student(Person):
    def __init__(self, name, age, course):
        super().__init__(name, age)   # Call parent constructor
        self.course = course

    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Course:", self.course)

# Create object
s = Student("Vaishnavi", 21, "BCA")

# Display details
s.display()

Name: Vaishnavi
Age: 21
Course: BCA

In [18]:
#16.Create multi-level inheritance: Person → Employee → Manager. Override a
#method at each level.

# Parent Class
class Person:
    def show(self):
        print("I am a Person")

# Child Class
class Employee(Person):
    def show(self):
        print("I am an Employee")

# Grandchild Class
class Manager(Employee):
    def show(self):
        print("I am a Manager")

# Create object
m = Manager()

# Call overridden method
m.show()

I am a Manager

In [20]:
#17.Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
#method.

# Parent Class
class Animal:
    def sound(self):
        print("Animal makes a sound")

# Child Class 1
class Dog(Animal):
    def sound(self):
        print("Dog barks....!!")

# Child Class 2
class Cat(Animal):
    def sound(self):
        print("Cat meows.......!!")

# Create objects
dog = Dog()
cat = Cat()

# Call overridden methods
dog.sound()
cat.sound()

Dog barks....!!
Cat meows.......!!

In [22]:
#18.Create abstract class Shape with abstract method area(). Implement it in Circle
#and Square using super().

from abc import ABC, abstractmethod

# Abstract Class
class Shape(ABC):
    def __init__(self, value):
        self.value = value

    @abstractmethod
    def area(self):
        pass

# Circle Class
class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius)

    def area(self):
        return 3.14 * self.value * self.value

# Square Class
class Square(Shape):
    def __init__(self, side):
        super().__init__(side)

    def area(self):
        return self.value * self.value

# Create objects
c = Circle(7)
s = Square(5)

print("Circle Area:", c.area())
print("Square Area:", s.area())

Circle Area: 153.86
Square Area: 25

In [23]:
#19.Create multiple inheritance with two classes Father and Mother. Create child
#class and resolve method conflict.


# Parent Class 1
class Father:
    def show(self):
        print("This is Father's method")

# Parent Class 2
class Mother:
    def show(self):
        print("This is Mother's method")

# Child Class
class Child(Father, Mother):
    def show(self):
        super().show()    # Calls Father's method (MRO)
        print("This is Child's method")

# Create object
c = Child()
c.show()

This is Father's method
This is Child's method

In [ ]:
# Overloading + Exception + File Handling (20-25)

In [24]:
#20.Create a class Calculator that can add 2 or 3 numbers (method overloading
#using *args).

# Calculator Class
class Calculator:

    def add(self, *args):
        if len(args) == 2:
            print("Sum of 2 numbers:", args[0] + args[1])
        elif len(args) == 3:
            print("Sum of 3 numbers:", args[0] + args[1] + args[2])
        else:
            print("Please enter only 2 or 3 numbers.")

# Create object
c = Calculator()

# Add 2 numbers
c.add(10, 20)

# Add 3 numbers
c.add(10, 20, 30)

# Invalid input
c.add(10)

Sum of 2 numbers: 30
Sum of 3 numbers: 60
Please enter only 2 or 3 numbers.

In [25]:
#21.Create class Point and overload + and > operators.

# Point Class
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    # Overload + operator
    def __add__(self, other):
        return Point(self.x + other.x, self.y + other.y)

    # Overload > operator
    def __gt__(self, other):
        return (self.x + self.y) > (other.x + other.y)

    def display(self):
        print("Point(", self.x, ",", self.y, ")")

# Create objects
p1 = Point(2, 3)
p2 = Point(4, 5)

# + operator
p3 = p1 + p2
print("After Addition:")
p3.display()

# > operator
if p1 > p2:
    print("p1 is greater than p2")
else:
    print("p2 is greater than or equal to p1")

After Addition:
Point( 6 , 8 )
p2 is greater than or equal to p1

In [26]:
#22.Write a program that handles ZeroDivisionError, ValueError and IndexError using
#multiple except blocks.

try:
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))

    result = num1 / num2
    print("Result:", result)

    my_list = [10, 20, 30]
    index = int(input("Enter list index: "))
    print("Element:", my_list[index])

except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

except ValueError:
    print("Error: Please enter valid integer values.")

except IndexError:
    print("Error: List index is out of range.")

Enter first number:  6
Enter second number:  7

Result: 0.8571428571428571

Enter list index:  7

Error: List index is out of range.

In [29]:
#23.Create a custom exception InvalidAgeError. Raise it if age is less than 18.

# Custom Exception
class InvalidAgeError(Exception):
    pass

try:
    age = int(input("Enter your age: "))

    if age < 18:
        raise InvalidAgeError("Age must be 18 or above.")

    print("You are eligible.")

except InvalidAgeError as e:
    print("Error:", e)

except ValueError:
    print("Please enter a valid number.")

Enter your age:  22

You are eligible.

In [12]:
#24.Write a program to read a file, count number of words, and write the count into
#another file.

file = open("C:\\Users\\Dell\\Downloads\\input.txt", "r")
text = file.read()
file.close()

count = len(text.split())

file = open("C:\\Users\\Dell\\Downloads\\output.txt", "w")
file.write("Word Count = " + str(count))
file.close()

print("Word Count =", count)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dell\\Downloads\\input.txt'

In [33]:
#25.Create a menu-driven program for file operations: Write, Read, Append, and Exit.
#Handle FileNotFoundError.

while True:
    print("\n----- MENU -----")
    print("1. Write to File")
    print("2. Read File")
    print("3. Append to File")
    print("4. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        text = input("Enter text to write: ")
        file = open("data.txt", "w")
        file.write(text)
        file.close()
        print("Data written successfully.")

    elif choice == 2:
        try:
            file = open("data.txt", "r")
            print("\nFile Content:")
            print(file.read())
            file.close()
        except FileNotFoundError:
             print("Error: File does not exist.")

    elif choice == 3:
        text = input("Enter text to append: ")
        file = open("data.txt", "a")
        file.write("\n" + text)
        file.close()
        print("Data appended successfully.")

    elif choice == 4:
        print("Program Exited.")
        break

    else:
        print("Invalid Choice!")

----- MENU -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  6

Invalid Choice!

----- MENU -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  7

Invalid Choice!

----- MENU -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  8

Invalid Choice!

----- MENU -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  0

Invalid Choice!

----- MENU -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  4

Program Exited.