In [ ]:
#Allowed methods only:
#pd.DataFrame(), pd.read_csv(), head(), tail(), sample(), info(), isnull(), isna(), select_dtypes(),
#describe(), drop(), duplicated(), drop_duplicates(), value_counts(), rename(), add_prefix(),
#astype(), fillna(), mean(), median()

In [18]:
import pandas as pd
DataFrame= df

In [16]:
df=pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")

In [17]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [25]:
#1.Load the dataset and display the first 10 records.

import pandas as pd

# Load the dataset
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")  # Replace "data.csv" with your dataset file name

# Display the first 10 records
print(df.head(10))

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0
1   37    1   2       130   250    0        1      187      0      3.5      0
2   41    0   1       130   204    0        0      172      0      1.4      2
3   56    1   1       120   236    0        1      178      0      0.8      2
4   57    0   0       120   354    0        1      163      1      0.6      2
5   57    1   0       140   192    0        1      148      0      0.4      1
6   56    0   1       140   294    0        0      153      0      1.3      1
7   44    1   1       120   263    0        1      173      0      0.0      2
8   52    1   2       172   199    1        1      162      0      0.5      2
9   57    1   2       150   168    0        1      174      0      1.6      2

   ca  thal  target
0   0     1       1
1   0     2       1
2   0     2       1
3   0     2       1
4   0     2       1
5   0     1       1
6   0     2       1
7   0     3       1
8   0     3       1
9   0     2       1

In [26]:
#2.Display the last 15 customers.

df.tail(15)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
288,57,1,0,110,335,0,1,143,1,3.0,1,1,3,0
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3,0
290,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [29]:
#3.Show 7 random customer records.

df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
149,42,1,2,130,180,0,1,150,0,0.0,2,0,2,1

In [31]:
#4.Print complete dataset information and identify:
#• Total columns
#• Data type of each column
#• Missing values

df.info

<bound method DataFrame.info of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [36]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [39]:
df.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [40]:
#5.Find missing values in every column.

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [48]:
#6.Display only numerical columns.

df.select_dtypes(include=["float"])

     oldpeak
0        2.3
1        3.5
2        1.4
3        0.8
4        0.6
..       ...
298      0.2
299      1.2
300      3.4
301      1.2
302      0.0

[303 rows x 1 columns]

In [49]:
#7.Generate the statistical summary of numerical columns.

df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [50]:
#8.Find duplicate rows and print how many exist.

df.duplicated().sum()

np.int64(1)

In [51]:
#9.Remove duplicate rows and store the cleaned dataset.

# Load the dataset
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")   # Replace with my dataset file name

# Remove duplicate rows
cleaned_df = df.drop_duplicates()

# Display the cleaned dataset
print(cleaned_df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[302 rows x 14 columns]

In [63]:
#10.Count how many customers have exited and how many have not exited.

import pandas as pd

df = pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")   
df["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [ ]:
# mediam level(11-20)

In [65]:
#11.
#Rename the following columns:
#CustomerId → Customer_ID
#CreditScore → Credit_Score
#EstimatedSalary → Salary
#Exited → Churn

import pandas as pd

# Load the dataset
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")  

# Rename columns
df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Churn"
}, inplace=True)

df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [66]:
df.rename(columns={
    "age": "Age",
    "sex": "Gender",
    "trestbps": "Blood_Pressure",
    "chol": "Cholesterol",
    "target": "Heart_Disease"
}, inplace=True)

print(df.columns)

Index(['Age', 'Gender', 'cp', 'Blood_Pressure', 'Cholesterol', 'fbs',
       'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal',
       'Heart_Disease'],
      dtype='object')

In [68]:
#12.
#Add the prefix
#Bank_
#to every column name.

import pandas as pd

# Load the dataset
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\dataset.csv")

# Add prefix 'Bank_' to all column names
df = df.add_prefix("Bank_")

# Display updated column names
print(df.columns)

Index(['Bank_age', 'Bank_sex', 'Bank_cp', 'Bank_trestbps', 'Bank_chol',
       'Bank_fbs', 'Bank_restecg', 'Bank_thalach', 'Bank_exang',
       'Bank_oldpeak', 'Bank_slope', 'Bank_ca', 'Bank_thal', 'Bank_target'],
      dtype='object')

In [71]:
#13.Convert the Age column into float datatype.

df["age"] = df["age"].astype(float)
df.dtypes

age         float64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [75]:
#14.Convert the target column into string datatype.

df["target"]=df["target"].astype(str)
df.dtypes

age         float64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target       object
dtype: object

In [90]:
#15.Suppose the Balance column has missing values.
#Replace them using the mean of the Balance column.

print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [84]:
print(df.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [87]:
print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [93]:
print(df['chol'].mean())

246.26402640264027

In [92]:
df['chol']

0      233
1      250
2      204
3      236
4      354
      ...
298    241
299    264
300    193
301    131
302    236
Name: chol, Length: 303, dtype: int64

In [96]:
#16.Suppose the Age column has missing values.
#Replace them using the median age.

df['age'] = df['age'].fillna(df['age'].median())
df['age']

0      63.0
1      37.0
2      41.0
3      56.0
4      57.0
       ...
298    57.0
299    45.0
300    68.0
301    57.0
302    57.0
Name: age, Length: 303, dtype: float64

In [99]:
#17.Display only the first five rows after renaming the columns.

# Rename columns
df = df.rename(columns={
    'age': 'Age',
    'sex': 'Gender',
    'chol': 'Cholesterol'
})

# Display first five rows
df.head(5)

,Age,Gender,cp,trestbps,Cholesterol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [102]:
#18.Create a new DataFrame by dropping these columns:
#RowNumber
#CustomerId
#Surname
#Display the first 10 rows.

df.head(10)

,Age,Gender,cp,trestbps,Cholesterol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57.0,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56.0,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44.0,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52.0,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57.0,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [107]:
#19.Drop the Geography column and display dataset information again.

# Display dataset information again
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          303 non-null    float64
 1   Sex          303 non-null    int64
 2   cp           303 non-null    int64
 3   trestbps     303 non-null    int64
 4   Cholesterol  303 non-null    int64
 5   fbs          303 non-null    int64
 6   restecg      303 non-null    int64
 7   thalach      303 non-null    int64
 8   exang        303 non-null    int64
 9   oldpeak      303 non-null    float64
 10  slope        303 non-null    int64
 11  ca           303 non-null    int64
 12  thal         303 non-null    int64
 13  target       303 non-null    object
dtypes: float64(2), int64(11), object(1)
memory usage: 33.3+ KB

In [104]:
df.columns

Index(['Age', 'Gender', 'cp', 'trestbps', 'Cholesterol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [105]:
print(df.columns.tolist())

['Age', 'Gender', 'cp', 'trestbps', 'Cholesterol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [ ]:
# Hard Level (21–30)

In [118]:
#21.(Real Company Task)
#Your manager wants cleaner column names.
#Rename every column as follows:
#RowNumber → Row_No
#CustomerId → Customer_ID
#Surname → Last_Name
#CreditScore → Credit_Score
#Geography → Country
#Gender → Sex
#EstimatedSalary → Salary
#Exited → Target
#Display the first five rows.

df = df.rename(columns={
    'RowNumber': 'Row_No',
    'CustomerId': 'Customer_ID',
    'Surname': 'Last_Name',
    'CreditScore': 'Credit_Score',
    'Geography': 'Country',
    'Gender': 'Sex',
    'EstimatedSalary': 'Salary',
    'Exited': 'Target'
})

df.head(10)

,Age,Sex,cp,trestbps,Cholesterol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57.0,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56.0,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44.0,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52.0,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57.0,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [119]:
#22.Create a new DataFrame that contains only numeric columns.
#Then generate its statistical summary.

numeric_df = df.select_dtypes(include='number')
print(numeric_df.head())

    Age  Sex  cp  trestbps  Cholesterol  fbs  restecg  thalach  exang  \
0  63.0    1   3       145          233    1        0      150      0
1  37.0    1   2       130          250    0        1      187      0
2  41.0    0   1       130          204    0        0      172      0
3  56.0    1   1       120          236    0        1      178      0
4  57.0    0   0       120          354    0        1      163      1

   oldpeak  slope  ca  thal
0      2.3      0   0     1
1      3.5      0   0     2
2      1.4      2   0     2
3      0.8      2   0     2
4      0.6      2   0     2

In [120]:
#23.Your company received duplicate customer records.
#Tasks:
#• Count duplicates.
#• Remove duplicates.
#• Display dataset information after cleaning.

df.duplicated().sum()

np.int64(1)

In [126]:
df.drop_duplicates()

,Age,Sex,cp,trestbps,Cholesterol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45.0,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68.0,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57.0,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57.0,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [127]:
df.info

<bound method DataFrame.info of       Age  Sex  cp  trestbps  Cholesterol  fbs  restecg  thalach  exang  \
0    63.0    1   3       145          233    1        0      150      0
1    37.0    1   2       130          250    0        1      187      0
2    41.0    0   1       130          204    0        0      172      0
3    56.0    1   1       120          236    0        1      178      0
4    57.0    0   0       120          354    0        1      163      1
..    ...  ...  ..       ...          ...  ...      ...      ...    ...
298  57.0    0   0       140          241    0        1      123      1
299  45.0    1   3       110          264    0        1      132      0
300  68.0    1   0       144          193    1        1      141      0
301  57.0    1   0       130          131    0        1      115      1
302  57.0    0   1       130          236    0        0      174      0

     oldpeak  slope  ca  thal target
0        2.3      0   0     1      1
1        3.5      0   0     2      1
2        1.4      2   0     2      1
3        0.8      2   0     2      1
4        0.6      2   0     2      1
..       ...    ...  ..   ...    ...
298      0.2      1   0     3      0
299      1.2      1   0     3      0
300      3.4      1   2     3      0
301      1.2      1   1     3      0
302      0.0      1   1     2      0

[302 rows x 14 columns]>

In [130]:
#24.Management wants every column name to begin with
#Customer_
#Apply this transformation using the appropriate method.

df = df.add_prefix("Customer_")
df.head()

,Customer_Customer_Customer_Age,Customer_Customer_Customer_Sex,Customer_Customer_Customer_cp,Customer_Customer_Customer_trestbps,Customer_Customer_Customer_Cholesterol,Customer_Customer_Customer_fbs,Customer_Customer_Customer_restecg,Customer_Customer_Customer_thalach,Customer_Customer_Customer_exang,Customer_Customer_Customer_oldpeak,Customer_Customer_Customer_slope,Customer_Customer_Customer_ca,Customer_Customer_Customer_thal,Customer_Customer_Customer_target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [137]:
#25.After renaming the columns, convert
#Age
#Balance
#Salary
#to float datatype.
#Print dataset information.

df = df.astype({
    'Customer_Customer_Customer_Age': 'float'
})

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 302 entries, 0 to 302
Data columns (total 14 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Customer_Customer_Customer_Age          302 non-null    float64
 1   Customer_Customer_Customer_Sex          302 non-null    int64
 2   Customer_Customer_Customer_cp           302 non-null    int64
 3   Customer_Customer_Customer_trestbps     302 non-null    int64
 4   Customer_Customer_Customer_Cholesterol  302 non-null    int64
 5   Customer_Customer_Customer_fbs          302 non-null    int64
 6   Customer_Customer_Customer_restecg      302 non-null    int64
 7   Customer_Customer_Customer_thalach      302 non-null    int64
 8   Customer_Customer_Customer_exang        302 non-null    int64
 9   Customer_Customer_Customer_oldpeak      302 non-null    float64
 10  Customer_Customer_Customer_slope        302 non-null    int64
 11  Customer_Customer_Customer_ca           302 non-null    int64
 12  Customer_Customer_Customer_thal         302 non-null    int64
 13  Customer_Customer_Customer_target       302 non-null    object
dtypes: float64(2), int64(11), object(1)
memory usage: 35.4+ KB