In [5]:

import pandas as pd

df = pd.read_csv("C:\\Users\\Dell\\Downloads\\Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [25]:
#1.Challenge 1 – Complete Data Cleaning
#Your manager gives you a messy dataset.
#Perform all of the following:
#• Load the dataset.
#• Display dataset information.
#• Find missing values.
#• Remove duplicate rows.
#• Fill missing values:
#o Age → median
#o Balance → mean
#• Rename:
#o Target → CustomerStatus
#o AnnualIncome → Income
#• Display the first 15 rows.

import pandas as pd
#load the dataset
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\Task_dataset.csv")
df

#display dataset information
df.info

#Finding missing value
# Age → Median
df["Age"] = df["Age"].fillna(df["Age"].median())
df

#Remove duplicate row
df = df.drop_duplicates()
df

#Fill missing values:
#Age-median
df["Age"] = df["Age"].fillna(df["Age"].median())
df
#o Balance → mean
df["Balance"]=df["Balance"].fillna(df["Balance"].mean())
df

#• Rename
#o Target → CustomerStatus
#AnnualIncome → Income
df=df.rename(columns={
    "Target":"CustomerStatus",
    "AnnualIncome":"Income"
})
df

#• Display the first 15 rows.
df.head(15)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [32]:
#2.Challenge 2 – Banking Report
#The bank wants a numeric report.
#Tasks
#• Select only numeric columns.
#• Display summary statistics.
#• Convert Age and CreditScore to float.
#• Display information again.

# Select only numeric columns
numeric_df = df.select_dtypes(include="number")
df
#• Display summary statistics
numeric_df.describe()

#• Convert Age and CreditScore to float.
df["Age"] = df["Age"].astype(float)
df["CreditScore"] = df["CreditScore"].astype(float)
df

#• Display information again.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    CustomerID     1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

In [42]:
#3.Challenge 3 – Duplicate Investigation
#Find duplicate customers.
#Then
#• Count duplicate rows.
#• Remove duplicates.
#• Print information before and after removing duplicates.
#• Show the last 20 rows.

#Find duplicate customers.
df.duplicated()
df

#• Count duplicate rows.
duplicate_count = df.duplicated().sum()
df

#•Remove duplicates.
df = df.drop_duplicates()
df
#• Print information before and after removing duplicates
print("\nInformation AFTER removing duplicates:")
df.info()

#Show the last 20 rows.
df.tail(20)

Information AFTER removing duplicates:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    CustomerID     1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
980,10981,41.0,199633.0,8498,847.0,173390.590000,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541.0,59484.580000,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334.0,97557.565779,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732.0,175352.250000,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730.0,120423.190000,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488.0,126031.270000,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621.0,115161.870000,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720.0,158528.460000,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635.0,159905.730000,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884.0,44897.430000,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773.0,39653.240000,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452.0,17812.250000,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764.0,165451.490000,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594.0,149288.610000,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493.0,83666.200000,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

In [57]:
#4.Challenge 4 – HR Department
#HR wants better column names.
#Rename
#CustomerID → Employee_ID
#Age → EmployeeAge
#Gender → EmployeeGender
#AnnualIncome → Salary
#Target → PromotionStatus
#Then
#• Add prefix
#HR_
#to every column.
#Display 10 random records.

#Rename columns
df=df.rename(columns={
    "CustomerID":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"
})
df

#• Add prefix
#HR_
#to every column.
df=df.add_prefix("HR_")

##Display 10 random records.
df.sample(10)

,HR_HR_HRHR_HR_HR_ CustomerID,HR_HR_HRHR_HR_HR_EmployeeAge,HR_HR_HRHR_HR_HR_Income,HR_HR_HRHR_HR_HR_Spending,HR_HR_HRHR_HR_HR_CreditScore,HR_HR_HRHR_HR_HR_Balance,HR_HR_HRHR_HR_HR_Tenure,HR_HR_HRHR_HR_HR_Geography,HR_HR_HRHR_HR_HR_EmployeeGender,HR_HR_HRHR_HR_HR_Segment,HR_HR_HRHR_HR_HR_CustomerStatus
227,10228,45.0,63684.0,45704,754.0,70309.400000,0,France,Female,SME,Churn
465,10466,23.0,188261.0,36159,696.0,97557.565779,6,UK,Male,Corporate,Stay
95,10096,30.0,102719.0,8335,848.0,190175.510000,2,USA,Male,SME,Stay
990,10991,58.0,79954.0,6331,773.0,39653.240000,2,India,Female,SME,Stay
358,10359,27.0,110431.0,2109,794.0,20909.870000,6,India,Male,SME,Stay
606,10607,55.0,38046.0,15561,687.0,77092.380000,1,India,Male,SME,Churn
71,10072,44.0,126849.0,22184,855.0,93184.860000,0,USA,Female,Corporate,Churn
751,10752,67.0,33450.0,27997,615.0,61903.660000,7,UK,Other,Retail,Stay
290,10291,46.0,158457.0,46622,670.0,15620.540000,9,India,Male,SME,Churn
404,10405,20.0,35851.0,26581,818.0,57297.560000,8,Canada,Female,SME,Stay

In [63]:
#5.Challenge 5 – Finance Cleaning
#Finance department reports missing values.
#Tasks
#Fill
#AnnualIncome → Median
#Balance → Mean
#Age → Median
#Then
#Generate descriptive statistics.


df.columns = [
    "CustomerID",
    "Age",
    "Income",
    "Spending",
    "CreditScore",
    "Balance",
    "Tenure",
    "Geography",
    "Gender",
    "Segment",
    "Target"
]

df.columns

# AnnualIncome/Income → Median
df["Income"] = df["Income"].fillna(df["Income"].median())

# Balance → Mean
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

# Age → Median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Generate descriptive statistics
print("Descriptive Statistics:")
print(df.describe())

Descriptive Statistics:
         CustomerID          Age         Income      Spending  CreditScore  \
count   1000.000000  1000.000000    1000.000000   1000.000000  1000.000000
mean   10500.500000    44.202000  112452.763000  25285.558000   603.088000
std      288.819436    15.130834   51081.480963  14211.735656   176.605486
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10250.750000    31.000000   68437.250000  13213.000000   441.000000
50%    10500.500000    44.000000  112347.500000  24901.000000   606.500000
75%    10750.250000    57.000000  155570.750000  37960.250000   758.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1000.000000  1000.000000
mean    97557.565779     5.241000
std     54430.062006     3.179155
min       547.600000     0.000000
25%     52074.240000     2.000000
50%     97557.565779     5.000000
75%    142297.910000     8.000000
max    199885.880000    10.000000

In [69]:
#6.Challenge 6 – Data Type Audit
#The company says
#Age and AnnualIncome are stored incorrectly.
#Tasks
#Convert
#Age → int
#AnnualIncome → float
#Balance → float
#Target → string
#Print information.

# Convert data types
df["Age"] = df["Age"].astype(int)
df["Income"] = df["Income"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

# Print information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   1000 non-null   int64
 1   Age          1000 non-null   int64
 2   Income       1000 non-null   float64
 3   Spending     1000 non-null   int64
 4   CreditScore  1000 non-null   float64
 5   Balance      1000 non-null   float64
 6   Tenure       1000 non-null   int64
 7   Geography    950 non-null    object
 8   Gender       950 non-null    object
 9   Segment      950 non-null    object
 10  Target       1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [75]:
#7.Challenge 7 – Customer Analytics
#Create a new DataFrame that
#• removes Segment
#• removes Geography
#• removes duplicate rows
#Display
#• first 10 rows
#dataset information
#• statistical summary

# New DataFrame create karo
df_new = df.drop(columns=["Segment", "Geography"])

#• removes duplicate rows
df_new = df_new.drop_duplicates()

#first 10 rows
df_new.head(10)

#dataset information
df_new.info

##• statistical summary
df_new.describe()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [17]:
#8.Challenge 8 – ML Dataset Preparation
#Prepare a machine learning dataset.
#Perform
#• Remove duplicates
#• Remove CustomerID
#• Remove Segment
#• Fill missing values
#• Rename Target to Output
#Finally
#Display
#head()
#info()
#describe()
#value_counts(Output)

import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\Task_dataset.csv")

df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [15]:
print(df.columns)

Index([' CustomerID ', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'Gender', 'Segment', 'Target'],
      dtype='object')

In [21]:
# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Copy dataset
ml_df = df.copy()

# Remove duplicates
ml_df = ml_df.drop_duplicates()

# Remove CustomerID
ml_df = ml_df.drop(columns=["CustomerID"])

# Remove Segment
ml_df = ml_df.drop(columns=["Segment"])

# Fill missing values
ml_df["Age"] = ml_df["Age"].fillna(ml_df["Age"].median())
ml_df["AnnualIncome"] = ml_df["AnnualIncome"].fillna(ml_df["AnnualIncome"].median())
ml_df["Balance"] = ml_df["Balance"].fillna(ml_df["Balance"].mean())
ml_df["Geography"] = ml_df["Geography"].fillna(ml_df["Geography"].mode()[0])

# Rename Target to Output
ml_df = ml_df.rename(columns={"Target": "Output"})

# Display first 5 rows
#head()
ml_df.head(5)
#info()
ml_df.info()
#describe()
ml_df.describe()
#value_counts
ml_df["Output"].value_counts()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           1000 non-null   float64
 1   AnnualIncome  1000 non-null   float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       1000 non-null   float64
 5   Tenure        1000 non-null   int64
 6   Geography     1000 non-null   object
 7   Gender        950 non-null    object
 8   Output        1000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 78.1+ KB

Output
Churn    506
Stay     494
Name: count, dtype: int64

In [22]:
#9.Challenge 9 – Column Transformation
#Create these new columns
#NetWorth = Balance + AnnualIncome
#AgeAfterRetirement = Age + 20
#DoubleCreditScore = CreditScore * 2
#IncomePerMonth = AnnualIncome / 12
#Then
#Display first 15 rows.


# Create new columns
ml_df["NetWorth"] = ml_df["Balance"] + ml_df["AnnualIncome"]

ml_df["AgeAfterRetirement"] = ml_df["Age"] + 20

ml_df["DoubleCreditScore"] = ml_df["CreditScore"] * 2

ml_df["IncomePerMonth"] = ml_df["AnnualIncome"] / 12

# Display first 15 rows
ml_df.head(15)

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58.0,49184.0,2139,581,97557.565779,2,France,Male,Stay,146741.565779,78.0,1162,4098.666667
1,65.0,162964.0,6197,732,6356.540000,1,USA,Male,Churn,169320.540000,85.0,1464,13580.333333
2,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,170159.920000,76.0,1006,2246.333333
3,55.0,92926.0,925,463,139627.880000,5,India,Male,Churn,232553.880000,75.0,926,7743.833333
4,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Churn,184221.460000,86.0,788,9019.666667
5,69.0,31390.0,48323,770,107245.620000,6,India,Other,Stay,138635.620000,89.0,1540,2615.833333
6,58.0,182141.0,24200,891,38457.720000,1,India,Other,Churn,220598.720000,78.0,1782,15178.416667
7,67.0,95861.0,5729,538,173296.730000,6,UK,Female,Stay,269157.730000,87.0,1076,7988.416667
8,41.0,62638.0,24760,663,41901.410000,4,France,Other,Stay,104539.410000,61.0,1326,5219.833333
9,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Churn,286507.980000,42.0,950,14973.333333
10,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Stay,231695.030000,64.0,1740,15647.666667
11,69.0,102694.0,26790,574,13237.720000,9,France,Female,Churn,115931.720000,89.0,1148,8557.833333
12,59.0,150870.0,26428,769,28574.320000,2,USA,Other,Stay,179444.320000,79.0,1538,12572.500000
13,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Stay,174562.770000,72.0,1796,7406.333333
14,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Churn,304725.430000,46.0,786,12797.416667

In [23]:
#10.Challenge 10 – Company Report
#Display
#• first five rows
#• last five rows
#• ten random rows
#• dataset information
#• descriptive statistics
#Finally rename
#Target → Customer_Status

# First five rows
ml_df.head(5)

# Last five rows
ml_df.tail(5)

# Ten random rows
ml_df.sample(10)

# Dataset information
ml_df.info()

# Descriptive statistics
ml_df.describe()

# Rename Target → Customer_Status
ml_df = ml_df.rename(columns={"Target": "Customer_Status"})

# Display final columns
ml_df.columns

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1000 non-null   float64
 1   AnnualIncome        1000 non-null   float64
 2   Spending            1000 non-null   int64
 3   CreditScore         1000 non-null   int64
 4   Balance             1000 non-null   float64
 5   Tenure              1000 non-null   int64
 6   Geography           1000 non-null   object
 7   Gender              950 non-null    object
 8   Output              1000 non-null   object
 9   NetWorth            1000 non-null   float64
 10  AgeAfterRetirement  1000 non-null   float64
 11  DoubleCreditScore   1000 non-null   int64
 12  IncomePerMonth      1000 non-null   float64
dtypes: float64(6), int64(4), object(3)
memory usage: 109.4+ KB

Index(['Age', 'AnnualIncome', 'Spending', 'CreditScore', 'Balance', 'Tenure',
       'Geography', 'Gender', 'Output', 'NetWorth', 'AgeAfterRetirement',
       'DoubleCreditScore', 'IncomePerMonth'],
      dtype='object')

In [25]:
#11.Challenge 11 – Missing Value Report
#Create a report showing
#• Total missing values
#• Numerical columns
#• Mean of Balance
#• Median of Age
#• Fill missing values
#• Display information again


# Total missing values
ml_df.isnull().sum()

# Numerical columns
ml_df.select_dtypes(include="number").columns

# Mean of Balance
ml_df["Balance"].mean()

# Median of Age
ml_df["Age"].median()

# Fill missing values
ml_df["Balance"] = ml_df["Balance"].fillna(ml_df["Balance"].mean())
ml_df["Age"] = ml_df["Age"].fillna(ml_df["Age"].median())

# Display information
ml_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1000 non-null   float64
 1   AnnualIncome        1000 non-null   float64
 2   Spending            1000 non-null   int64
 3   CreditScore         1000 non-null   int64
 4   Balance             1000 non-null   float64
 5   Tenure              1000 non-null   int64
 6   Geography           1000 non-null   object
 7   Gender              950 non-null    object
 8   Output              1000 non-null   object
 9   NetWorth            1000 non-null   float64
 10  AgeAfterRetirement  1000 non-null   float64
 11  DoubleCreditScore   1000 non-null   int64
 12  IncomePerMonth      1000 non-null   float64
dtypes: float64(6), int64(4), object(3)
memory usage: 109.4+ KB

In [35]:
#12.Challenge 12 – Customer Classification
#Count
#Stay
#Churn
#Then
#Rename
#Target → Customer_Class
#Convert it into string.

# Count Stay and Churn
print("Stay:", (ml_df["Customer_Class"] == "Stay").sum())
print("Churn:", (ml_df["Customer_Class"] == "Churn").sum())

# Convert to string
ml_df["Customer_Class"] = ml_df["Customer_Class"].astype(str)

# Check datatype
print(ml_df["Customer_Class"].dtype)

Stay: 494
Churn: 506
object

In [37]:
#13.Challenge 13 – Sales Department
#Rename
#Balance → AccountBalance
#AnnualIncome → Salary
#CreditScore → Score
#Add prefix
#Sales_
#Then
#Display
#sample(20)

# Rename columns
ml_df = ml_df.rename(columns={
    "Balance": "AccountBalance",
    "AnnualIncome": "Salary",
    "CreditScore": "Score"
})

# Add Sales_ prefix to all columns
ml_df = ml_df.add_prefix("Sales_")

# Display 20 random rows
ml_df.sample(20)

,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Customer_Class,Sales_NetWorth,Sales_AgeAfterRetirement,Sales_DoubleCreditScore,Sales_IncomePerMonth
423,23.0,31508.0,15669,832,82611.360000,5,Canada,Other,Stay,114119.360000,43.0,1664,2625.666667
309,44.0,129185.0,37022,842,26818.550000,3,UK,Male,Stay,156003.550000,64.0,1684,10765.416667
140,26.0,184691.0,6867,340,61786.580000,7,India,Other,Churn,246477.580000,46.0,680,15390.916667
68,48.0,137983.0,17486,553,167972.580000,4,Germany,Female,Stay,305955.580000,68.0,1106,11498.583333
938,18.0,196726.0,32720,407,79273.950000,8,India,Other,Churn,275999.950000,38.0,814,16393.833333
54,34.0,30028.0,7604,744,69137.420000,5,Canada,Other,Stay,99165.420000,54.0,1488,2502.333333
701,56.0,24273.0,34422,438,198682.400000,4,India,Female,Churn,222955.400000,76.0,876,2022.750000
447,69.0,54207.0,22831,481,183756.160000,5,India,Male,Churn,237963.160000,89.0,962,4517.250000
358,27.0,110431.0,2109,794,20909.870000,6,India,Male,Stay,131340.870000,47.0,1588,9202.583333
882,41.0,65945.0,42978,872,140974.730000,8,India,Male,Stay,206919.730000,61.0,1744,5495.416667
489,32.0,86162.0,40368,612,142548.100000,10,UK,Female,Stay,228710.100000,52.0,1224,7180.166667
556,63.0,189772.0,24600,859,147690.010000,3,France,NaN,Stay,337462.010000,83.0,1718,15814.333333
904,50.0,123395.0,13243,802,63551.560000,9,Germany,Male,Stay,186946.560000,70.0,1604,10282.916667
804,31.0,193667.0,11864,786,27813.770000,8,Canada,Female,Stay,221480.770000,51.0,1572,16138.916667
655,24.0,45048.0,4680,784,109686.750000,0,Canada,Other,Churn,154734.750000,44.0,1568,3754.000000
617,46.0,62413.0,7071,519,101668.710000,5,Germany,Other,Stay,164081.710000,66.0,1038,5201.083333
401,49.0,121157.0,7888,546,97557.565779,9,India,Other,Stay,218714.565779,69.0,1092,10096.416667
454,28.0,186772.0,6314,643,89325.990000,4,USA,Male,Stay,276097.990000,48.0,1286,15564.333333
37,51.0,102934.0,17589,509,133945.190000,5,USA,Female,Stay,236879.190000,71.0,1018,8577.833333
381,50.0,198074.0,6740,438,192554.400000,6,India,Female,Churn,390628.400000,70.0,876,16506.166667

In [39]:
#14.Challenge 14 – Interview Challenge
#Without creating another DataFrame,
#perform
#• remove duplicates
#• rename Target
#• fill missing values
#• convert Balance to float
#• display summary

#Remove duplicates
ml_df.drop_duplicates(inplace=True)

# Rename Target/Output
if "Sales_Output" in ml_df.columns:
    ml_df.rename(columns={"Sales_Output": "Sales_Customer_Status"}, inplace=True)

# Fill missing values
if "Sales_Age" in ml_df.columns:
    ml_df["Sales_Age"] = ml_df["Sales_Age"].fillna(ml_df["Sales_Age"].median())

if "Sales_AccountBalance" in ml_df.columns:
    ml_df["Sales_AccountBalance"] = ml_df["Sales_AccountBalance"].fillna(
        ml_df["Sales_AccountBalance"].mean()
    )

# Convert Balance to float
if "Sales_AccountBalance" in ml_df.columns:
    ml_df["Sales_AccountBalance"] = ml_df["Sales_AccountBalance"].astype(float)

# Display summary
ml_df.info()
ml_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sales_Age                 1000 non-null   float64
 1   Sales_Salary              1000 non-null   float64
 2   Sales_Spending            1000 non-null   int64
 3   Sales_Score               1000 non-null   int64
 4   Sales_AccountBalance      1000 non-null   float64
 5   Sales_Tenure              1000 non-null   int64
 6   Sales_Geography           1000 non-null   object
 7   Sales_Gender              950 non-null    object
 8   Sales_Customer_Class      1000 non-null   object
 9   Sales_NetWorth            1000 non-null   float64
 10  Sales_AgeAfterRetirement  1000 non-null   float64
 11  Sales_DoubleCreditScore   1000 non-null   int64
 12  Sales_IncomePerMonth      1000 non-null   float64
dtypes: float64(6), int64(4), object(3)
memory usage: 109.4+ KB

,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_NetWorth,Sales_AgeAfterRetirement,Sales_DoubleCreditScore,Sales_IncomePerMonth
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000,210010.328779,64.202000,1206.176000,9371.063583
std,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155,73150.769298,15.130834,353.210972,4256.790080
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,38.000000,600.000000,1685.583333
25%,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000,156611.867500,51.000000,882.000000,5703.104167
50%,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000,209916.897889,64.000000,1213.000000,9362.291667
75%,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000,263542.793945,77.000000,1516.500000,12964.229167
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,90.000000,1800.000000,16663.916667

In [41]:
#15.Challenge 15 – Data Engineer Task
#Load the dataset.
#Create another DataFrame containing only numeric columns.
#Drop
#CustomerID
#Target
#Display summary.

# Create another DataFrame with only numeric columns
numeric_df = df.select_dtypes(include="number").copy()

# Drop CustomerID
numeric_df = numeric_df.drop(columns=["CustomerID"], errors="ignore")

# Drop Target
numeric_df = numeric_df.drop(columns=["Target"], errors="ignore")

# Display summary
numeric_df.head()
numeric_df.info()
numeric_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           970 non-null    float64
 1   AnnualIncome  967 non-null    float64
 2   Spending      1020 non-null   int64
 3   CreditScore   1020 non-null   int64
 4   Balance       969 non-null    float64
 5   Tenure        1020 non-null   int64
dtypes: float64(3), int64(3)
memory usage: 47.9 KB

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [44]:
#16.Challenge 16 – Mixed Cleaning
#Perform
#drop_duplicates()
#fillna()
#astype()
#rename()
#head()
#info()
#using only one DataFrame variable.

# Remove duplicates
ml_df = ml_df.drop_duplicates()

# Fill missing values
ml_df["Sales_Age"] = ml_df["Sales_Age"].fillna(ml_df["Sales_Age"].median())
ml_df["Sales_AccountBalance"] = ml_df["Sales_AccountBalance"].fillna(
    ml_df["Sales_AccountBalance"].mean()
)

# Convert AccountBalance to float
ml_df["Sales_AccountBalance"] = ml_df["Sales_AccountBalance"].astype(float)

# Rename column
ml_df = ml_df.rename(columns={
    "Sales_Customer_Class": "Sales_Customer_Status"
})

# Display first 5 rows
ml_df.head(5)

# Display information
ml_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sales_Age                 1000 non-null   float64
 1   Sales_Salary              1000 non-null   float64
 2   Sales_Spending            1000 non-null   int64
 3   Sales_Score               1000 non-null   int64
 4   Sales_AccountBalance      1000 non-null   float64
 5   Sales_Tenure              1000 non-null   int64
 6   Sales_Geography           1000 non-null   object
 7   Sales_Gender              950 non-null    object
 8   Sales_Customer_Status     1000 non-null   object
 9   Sales_NetWorth            1000 non-null   float64
 10  Sales_AgeAfterRetirement  1000 non-null   float64
 11  Sales_DoubleCreditScore   1000 non-null   int64
 12  Sales_IncomePerMonth      1000 non-null   float64
dtypes: float64(6), int64(4), object(3)
memory usage: 109.4+ KB

In [46]:
#17.Challenge 17 – Real Company Dataset
#Manager asks
#Remove duplicate records
#Fill missing values
#Rename all business columns
#Add company prefix
#Display summary
#Display target counts


# 1. Remove duplicate records
df = df.drop_duplicates()

# 2. Fill missing values
df = df.fillna(0)

# 3. Rename all business columns
df = df.rename(columns={
    "CustomerID": "Company_CustomerID",
    "Age": "Company_Age",
    "Income": "Company_Income",
    "Spending": "Company_Spending",
    "CreditScore": "Company_CreditScore",
    "Balance": "Company_Balance",
    "Tenure": "Company_Tenure",
    "Geography": "Company_Geography",
    "Gender": "Company_Gender",
    "Segment": "Company_Segment",
    "Target": "Company_Target"
})

# 4. Display summary
print(df.describe(include="all"))

# 5. Display target counts
print(df["Company_Target"].value_counts())

        Company_CustomerID  Company_Age   AnnualIncome  Company_Spending  \
count          1000.000000  1000.000000    1000.000000       1000.000000
unique                 NaN          NaN            NaN               NaN
top                    NaN          NaN            NaN               NaN
freq                   NaN          NaN            NaN               NaN
mean          10500.500000    42.002000  106835.388000      25285.558000
std             288.819436    17.941123   56662.551688      14211.735656
min           10001.000000     0.000000       0.000000        537.000000
25%           10250.750000    28.000000   60393.750000      13213.000000
50%           10500.500000    43.000000  107245.000000      24901.000000
75%           10750.250000    57.000000  155570.750000      37960.250000
max           11000.000000    70.000000  199967.000000      49995.000000

        Company_CreditScore  Company_Balance  Company_Tenure  \
count           1000.000000      1000.000000     1000.000000
unique                  NaN              NaN             NaN
top                     NaN              NaN             NaN
freq                    NaN              NaN             NaN
mean             603.088000     92679.687490        5.241000
std              176.605486     58439.408092        3.179155
min              300.000000         0.000000        0.000000
25%              441.000000     43913.355000        2.000000
50%              606.500000     92217.615000        5.000000
75%              758.250000    142297.910000        8.000000
max              900.000000    199885.880000       10.000000

       Company_Geography Company_Gender Company_Segment Company_Target
count               1000           1000            1000           1000
unique                 7              4               4              2
top                India          Other             SME          Churn
freq                 166            330             355            506
mean                 NaN            NaN             NaN            NaN
std                  NaN            NaN             NaN            NaN
min                  NaN            NaN             NaN            NaN
25%                  NaN            NaN             NaN            NaN
50%                  NaN            NaN             NaN            NaN
75%                  NaN            NaN             NaN            NaN
max                  NaN            NaN             NaN            NaN
Company_Target
Churn    506
Stay     494
Name: count, dtype: int64

In [50]:
#18.Challenge 18 – Customer Summary
#Generate
#Mean Balance
#Median Balance
#Mean Age
#Median AnnualIncome

#Then
#fill missing values using these statistics.


# Calculate statistics
mean_balance = df["Company_Balance"].mean()
median_balance = df["Company_Balance"].median()
mean_age = df["Company_Age"].mean()
median_income = df["AnnualIncome"].median()

# Display statistics
print("Mean Balance:", mean_balance)
print("Median Balance:", median_balance)
print("Mean Age:", mean_age)
print("Median AnnualIncome:", median_income)

# Fill missing values using statistics
df["Company_Balance"] = df["Company_Balance"].fillna(mean_balance)
df["Company_Age"] = df["Company_Age"].fillna(mean_age)
df["AnnualIncome"] = df["AnnualIncome"].fillna(median_income)

# Check missing values
df.isnull().sum()

Mean Balance: 92679.68749000001
Median Balance: 92217.61499999999
Mean Age: 42.002
Median AnnualIncome: 107245.0

Company_CustomerID     0
Company_Age            0
AnnualIncome           0
Company_Spending       0
Company_CreditScore    0
Company_Balance        0
Company_Tenure         0
Company_Geography      0
Company_Gender         0
Company_Segment        0
Company_Target         0
dtype: int64

In [48]:
print(df.columns)

Index(['Company_CustomerID', 'Company_Age', 'AnnualIncome', 'Company_Spending',
       'Company_CreditScore', 'Company_Balance', 'Company_Tenure',
       'Company_Geography', 'Company_Gender', 'Company_Segment',
       'Company_Target'],
      dtype='object')

In [54]:
#19.Challenge 19 – Transformation Challenge
#Create
#Income_in_Lakhs
#Balance_in_Lakhs

#SeniorCitizen
#HighCreditScore
#where
#SeniorCitizen = Age + 0
#HighCreditScore = CreditScore * 1
#(No conditional statements.)


# Create Income_in_Lakhs
df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000

# Create Balance_in_Lakhs
df["Balance_in_Lakhs"] = df["Company_Balance"] / 100000

# Create SeniorCitizen
df["SeniorCitizen"] = df["Company_Age"] + 0

# Create HighCreditScore
df["HighCreditScore"] = df["Company_CreditScore"] * 1

# Display result
df.head()

,Company_CustomerID,Company_Age,AnnualIncome,Company_Spending,Company_CreditScore,Company_Balance,Company_Tenure,Company_Geography,Company_Gender,Company_Segment,Company_Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,0.00,2,France,Male,SME,Stay,0.49184,0.000000,58.0,581
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.88,5,0,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394

In [77]:
#20.Challenge 20 – Final Interview Project
#Your manager gives you a dirty customer dataset.
#Prepare the final dataset.
#Requirements
#Load dataset
#Check information
#Find missing values
#Remove duplicates
#Rename
#CustomerID
#AnnualIncome
#CreditScore
#Target
#Convert
#Age

#AnnualIncome
#Balance

#Fill missing values
#Remove
#Segment
#CustomerID
#Create new columns
#TotalMoney = Balance + AnnualIncome
#AgeAfter5Years = Age + 5
#MonthlyIncome = AnnualIncome / 12
#CreditScoreDouble = CreditScore * 2Display
#• Head
#• Tail
#• Sample
#• Describe
#• Target counts
#• Final information


import pandas as pd
import numpy as np

# 1. Load dataset
df = pd.read_csv(r"C:\Users\Dell\Downloads\Task_dataset.csv")

# Extra spaces from column names
df.columns = df.columns.str.strip()

# 2. Check information
print("Initial Information:")
df.info()

# 3. Find missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 4. Remove duplicates
df = df.drop_duplicates()

# 5. Rename columns
df = df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Annual_Income",
    "CreditScore": "Credit_Score",
    "Target": "Output"
})

# 6. Handle infinite values
df = df.replace([np.inf, -np.inf], np.nan)

# 7. Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Annual_Income"] = df["Annual_Income"].fillna(df["Annual_Income"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

# 8. Convert data types
df["Age"] = df["Age"].astype(int)
df["Annual_Income"] = df["Annual_Income"].astype(float)
df["Balance"] = df["Balance"].astype(float)

# 9. Remove Segment and CustomerID
df = df.drop(columns=["Segment", "Customer_ID"])

# 10. Create new columns
df["TotalMoney"] = df["Balance"] + df["Annual_Income"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["Annual_Income"] / 12
df["CreditScoreDouble"] = df["Credit_Score"] * 2

# 11. Head
df.head()

# 12. Tail
df.tail()

# 13. Sample
df.sample(5)

# 14. Describe
df.describe()

# 15. Target counts
df["Output"].value_counts()

# 16. Final Information
df.info()

Initial Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Missing Values:
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Annual_Income      1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   Credit_Score       1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Geography          950 non-null    object
 7   Gender             950 non-null    object
 8   Output             1000 non-null   object
 9   TotalMoney         1000 non-null   float64
 10  AgeAfter5Years     1000 non-null   int64
 11  MonthlyIncome      1000 non-null   float64
 12  CreditScoreDouble  1000 non-null   int64
dtypes: float64(4), int64(6), object(3)
memory usage: 109.4+ KB