In [ ]:
#Flight Price Datasets— 30 Clean Questions

In [19]:
#1.Load the Flight Price dataset into a Pandas DataFrame and display the first
#five rows.

import pandas as pd

df = pd.read_excel(r"C:\Users\Dell\Downloads\Data_Train.xlsx")

df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [16]:
import os

print(os.listdir(r"C:\Users\Dell\Downloads"))        #check the Dataset

['.ipynb_checkpoints', '3016_20062026105351.pdf', '4236_21032026080745.pdf', 'Advanced OOPs concept (1).ipynb', 'Advanced OOPs concept.ipynb', 'Anaconda3-2025.12-2-Windows-x86_64.exe', 'ChromeSetup.exe', 'cleaned_dataset.csv', 'customer_analytics.csv', 'dataset.csv', 'Data_Train.xlsx', 'Day 1.ipynb', 'debug.log', 'desktop.ini', 'GitHubDesktopSetup-x64.exe', 'MCA.pdf', 'Microsoft.Services.Store (1).winmd', 'Microsoft.Services.Store (2).winmd', 'Microsoft.Services.Store.winmd', 'Pandas Method (1).ipynb', 'Pandas Method.ipynb', 'Resume Template.docx', 'Task  on Class.pdf', 'Task_dataset.csv', 'Task_dataset.csv.pdf', 'TypingMaster12India (1).exe', 'TypingMaster12India.exe', 'VSCodeUserSetup-x64-1.131.0.exe', 'WhatsApp Installer (1).exe', 'WhatsApp Installer (2).exe', 'WhatsApp Installer.exe', '~$MCA.pdf', '~$sk  on Class.pdf']

In [29]:
#2.Find the number of rows and columns in the dataset.

#check the rows and columns in dataset
df.shape

(10683, 11)

In [30]:
#3.Display all column names in the dataset.

#display all column names 
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [31]:
#4.Display the data types of all columns.

#display all data types in columns
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [32]:
#5.Use df.info() to inspect the structure of the dataset.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [33]:
#6.Check the number of missing values in each column.
#check the missing values in each column
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [34]:
#7.Check the percentage of missing values in each column.

#check % of missing values
df.isnull().mean() * 100

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

In [35]:
#8.Display the unique values and frequency of each value in the Airline column.

df["Airline"].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [36]:
#9.Display the frequency distribution of Total_Stops, including missing values.

print(df["Total_Stops"].value_counts(dropna=False))

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

In [39]:
#10.Convert Date_of_Journey into a datetime format.

df["Date_of_Journey"] = pd.to_datetime(
    df["Date_of_Journey"],
    dayfirst=True
)

df["Date_of_Journey"].head()

0   2019-03-24
1   2019-05-01
2   2019-06-09
3   2019-05-12
4   2019-03-01
Name: Date_of_Journey, dtype: datetime64[ns]

In [40]:
#11.Extract the day from Date_of_Journey and create a day column.

df["day"] = df["Date_of_Journey"].dt.day
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1

In [41]:
#12.Extract the month from Date_of_Journey and create a month column.

df["month"] = df["Date_of_Journey"].dt.month
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3

In [43]:
#13.Extract the year from Date_of_Journey and create a year column.

df["year"] = df["Date_of_Journey"].dt.year
df.head(11)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
5,SpiceJet,2019-06-24,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873,24,6,2019
6,Jet Airways,2019-03-12,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087,12,3,2019
7,Jet Airways,2019-03-01,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270,1,3,2019
8,Jet Airways,2019-03-12,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087,12,3,2019
9,Multiple carriers,2019-05-27,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625,27,5,2019
10,Air India,2019-06-01,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907,1,6,2019

In [51]:
#14.Drop the original Date_of_Journey column after extracting the required
#features.

#drop the date_of_Journey columns
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'day', 'month',
       'year'],
      dtype='object')

In [54]:
#15.Convert Dep_Time into datetime format and extract the departure hour into
#Dep_Hour.

df["Dep_Time"] = pd.to_datetime(df["Dep_Time"], format="%H:%M")

df["Dep_Hour"] = df["Dep_Time"].dt.hour

df[["Dep_Time", "Dep_Hour"]].head()

             Dep_Time  Dep_Hour
0 2026-08-10 22:20:00        22
1 2026-08-10 05:50:00         5
2 2026-08-10 09:25:00         9
3 2026-08-10 18:05:00        18
4 2026-08-10 16:50:00        16

In [56]:
#16.Extract the departure minute from Dep_Time and create Dep_Minute.

df["Dep_Minute"] = df["Dep_Time"].dt.minute

df[["Dep_Time", "Dep_Hour", "Dep_Minute"]].head()

             Dep_Time  Dep_Hour  Dep_Minute
0 2026-08-10 22:20:00        22          20
1 2026-08-10 05:50:00         5          50
2 2026-08-10 09:25:00         9          25
3 2026-08-10 18:05:00        18           5
4 2026-08-10 16:50:00        16          50

In [66]:
#17.Drop the original Dep_Time column after extracting the required features.

##df = df.drop(columns=["Dep_Time"])       #drop the Dep_columns
##df.head

df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Arrival_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'day', 'month', 'year',
       'Dep_Hour', 'Dep_Minute'],
      dtype='object')

In [73]:
#18.Extract only the time portion from Arrival_Time.

df["Arrival_Time"] = df["Arrival_Time"].astype(str).str[:5]

df[["Arrival_Time"]].head()

  Arrival_Time
0        01:10
1        13:15
2        04:25
3        23:30
4        21:35

In [78]:
#19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

df["Arrival_Hour"] = pd.to_datetime(
    df["Arrival_Time"], format="%H:%M"
).dt.hour

df["Arrival_Minute"] = pd.to_datetime(
    df["Arrival_Time"], format="%H:%M"
).dt.minute

df[["Arrival_Time", "Arrival_Hour", "Arrival_Minute"]].head()

  Arrival_Time  Arrival_Hour  Arrival_Minute
0        01:10             1              10
1        13:15            13              15
2        04:25             4              25
3        23:30            23              30
4        21:35            21              35

In [79]:
#20.Drop the original Arrival_Time column after extracting the required features.

df = df.drop(columns=["Arrival_Time"])

df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35

In [80]:
#21.Extract the hour component from Duration and create Duration_Hour. Handle
#invalid or missing extracted values appropriately.

df["Duration_Hour"] = (
    df["Duration"]
    .astype(str)
    .str.extract(r"(\d+)\s*h", expand=False)
)

df["Duration_Hour"] = pd.to_numeric(
    df["Duration_Hour"], errors="coerce"
)

df["Duration_Hour"] = df["Duration_Hour"].fillna(0).astype(int)

df[["Duration", "Duration_Hour"]].head()

  Duration  Duration_Hour
0   2h 50m              2
1   7h 25m              7
2      19h             19
3   5h 25m              5
4   4h 45m              4

In [81]:
#22.Extract the minute component from Duration and create Duration_Minute.
#Handle invalid or missing extracted values appropriately.

df["Duration_Minute"] = (
    df["Duration"]
    .astype(str)
    .str.extract(r"(\d+)\s*h", expand=False)
)

df["Duration_Minute"] = pd.to_numeric(
    df["Duration_Minute"], errors="coerce"
)

df["Duration_Minute"] = df["Duration_Minute"].fillna(0).astype(int)

df[["Duration", "Duration_Minute"]].head()

  Duration  Duration_Minute
0   2h 50m                2
1   7h 25m                7
2      19h               19
3   5h 25m                5
4   4h 45m                4

In [82]:
#23.Drop the original Duration column after creating the numerical duration
#features.

df = df.drop(columns=["Duration"])
df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,22,20,1,10,2,2
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,50,13,15,7,7
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,25,4,25,19,19
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,5,23,30,5,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,50,21,35,4,4

In [83]:
#24.Replace non-stop in Total_Stops with 0 stops.

df["Total_Stops"] = df["Total_Stops"].replace("non-stop", 0)

df["Total_Stops"].value_counts(dropna=False)

Total_Stops
1 stop     5625
0          3491
2 stops    1520
3 stops      45
NaN           1
4 stops       1
Name: count, dtype: int64

In [85]:
#25.Extract only the numerical value from Total_Stops and convert the column into
#an integer data type. Handle missing or invalid values appropriately.

df["Total_Stops"] = (
    df["Total_Stops"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
)

df["Total_Stops"] = pd.to_numeric(
    df["Total_Stops"], errors="coerce"
)

df["Total_Stops"] = df["Total_Stops"].fillna(0).astype(int)
df["Total_Stops"].head()

0    0
1    0
2    0
3    0
4    0
Name: Total_Stops, dtype: int64

In [86]:
#26.Split the Route column using → as the separator and create Route_1,
#Route_2, Route_3, Route_4, and Route_5.

route_parts = df["Route"].str.split("→", expand=True)

df["Route_1"] = route_parts[0]
df["Route_2"] = route_parts[1]
df["Route_3"] = route_parts[2]
df["Route_4"] = route_parts[3]
df["Route_5"] = route_parts[4]

df[["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]].head()

  Route_1 Route_2 Route_3 Route_4 Route_5
0    BLR      DEL    None    None    None
1    CCU     IXR     BBI      BLR    None
2    DEL     LKO     BOM      COK    None
3    CCU     NAG      BLR    None    None
4    BLR     NAG      DEL    None    None

In [88]:
#27.Identify the missing values created in Route_3, Route_4, and Route_5 after
#splitting the route.

df[["Route_3", "Route_4", "Route_5"]].isnull().sum()

Route_3     3492
Route_4     9117
Route_5    10637
dtype: int64

In [89]:
#28.Replace the missing values in the route columns with an appropriate value
#such as None.

route_columns = ["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]

df[route_columns] = df[route_columns].fillna("None")

df[route_columns].head()

  Route_1 Route_2 Route_3 Route_4 Route_5
0    BLR      DEL    None    None    None
1    CCU     IXR     BBI      BLR    None
2    DEL     LKO     BOM      COK    None
3    CCU     NAG      BLR    None    None
4    BLR     NAG      DEL    None    None

In [92]:
#29.Drop the original Route column after creating and cleaning the route features.
df = df.drop(columns=["Route"])
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,22,20,1,10,2,2,BLR,DEL,None,None,None
1,Air India,Kolkata,Banglore,0,No info,7662,1,5,2019,5,50,13,15,7,7,CCU,IXR,BBI,BLR,None
2,Jet Airways,Delhi,Cochin,0,No info,13882,9,6,2019,9,25,4,25,19,19,DEL,LKO,BOM,COK,None
3,IndiGo,Kolkata,Banglore,0,No info,6218,12,5,2019,18,5,23,30,5,5,CCU,NAG,BLR,None,None
4,IndiGo,Banglore,New Delhi,0,No info,13302,1,3,2019,16,50,21,35,4,4,BLR,NAG,DEL,None,None

In [93]:
#30.After completing all data cleaning and feature engineering, separate the
#dataset into X (independent variables) and y (target variable), where Price
#is the target.

X = df.drop(columns=["Price"])
y = df["Price"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (10683, 19)
y shape: (10683,)