In [4]:
import pandas as pd

df=pd.read_csv("C:\\Users\\Dell\\Downloads\\customer_data.csv")
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [5]:
#1.Load the CSV using Pandas and display the first 10 rows.
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.283473578603065,44108.07924936186,793.2135772820182,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.630009830989785,80888.86263734727,850.0,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.520166822399105,50011.55555812526,796.7940989517157,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30823662701,482.3950728788773,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

In [6]:
#2.Check the number of rows and columns in the dataset.

#checkl the row & columns
df.shape

(2000, 15)

In [11]:
#3.Display all column names and identify which column names contain
#leading/trailing spaces or inconsistent capitalization.


#Display all column names
df.columns.tolist()

# Check leading/trailing spaces
for col in df.columns:
    if col != col.strip():
        print(repr(col))

# Check capitalization
for col in df.columns:
    print(col)

customer id
age
income_usd
credit score
tenure_years
monthly_visits
satisfaction
city
customer_segment
gender
is_active
churn_flag
signup_date
lead_source
notes_text

In [12]:
#4.Check the data type of every column using Pandas.
df.dtypes

customer id          object
age                  object
income_usd           object
credit score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
city                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

In [14]:
#5.Calculate the number and percentage of missing values in every column.

#missing values
df.isnull().sum()

#missing percentage
df.isnull().sum() / len(df) * 100

customer id          1.00
age                 16.55
income_usd          22.00
credit score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
city                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

In [21]:
#6.Find the rows where Customer ID is missing.

df["customer id"].isnull().sum()

np.int64(20)

In [23]:
#7.Remove leading/trailing whitespace from all column names and convert them
#to lowercase with underscores.

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [27]:
#8.Identify duplicate Customer ID values and count how many duplicates exist.

duplicate_ids = df.loc[df['customer_id'].duplicated(), 'customer_id']

print(duplicate_ids)

226     NaN
300     NaN
421     NaN
770     NaN
821     NaN
876     NaN
993     NaN
1023    NaN
1188    NaN
1202    NaN
1212    NaN
1248    NaN
1338    NaN
1346    NaN
1448    NaN
1451    NaN
1462    NaN
1564    NaN
1652    NaN
Name: customer_id, dtype: object

In [26]:
df.columns                                              #find how mnay columns in dataset

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [29]:
#9.Remove duplicate customer records while keeping the first occurrence.

df = df.drop_duplicates(keep='first')
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [32]:
#10.Find all unique values in the customer_segment column and identify
#inconsistent categories such as Consumer, consumer, consumer , etc.

# Find all unique values
print(df['customer_segment'].unique())

['consumer ' 'Consumer' 'Enterprise' 'SMB' nan 'SMB.' 'UNKNOWN']

In [35]:
df['customer_segment'] = (
    df['customer_segment']
    .str.strip()
    .str.lower()
    .replace('smb.', 'smb')
)
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,smb,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,smb,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,smb,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,consumer,NaN,yes,No,2024-02-22,???,good

In [36]:
print(df['customer_segment'].value_counts(dropna=False))            #check the customer_segment

customer_segment
consumer      787
smb           464
NaN           380
enterprise    293
unknown        76
Name: count, dtype: int64

In [39]:
#11.Clean the customer_segment column by standardizing capitalization and
#whitespace.


df['customer_segment'] = (
    df['customer_segment']
    .str.strip()
    .str.lower()
)
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,smb,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,smb,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,smb,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,consumer,NaN,yes,No,2024-02-22,???,good

In [41]:
print(df['customer_segment'].unique())

['consumer' 'enterprise' 'smb' nan 'unknown']

In [46]:
#12.Find all unique values in the gender column and convert them into consistent
#categories such as Male and Female.

df['gender'] = (
    df['gender']
    .str.strip()
    .str.lower()
    .replace({
        'm': 'Male',
        'male': 'Male',
        'f': 'Female',
        'female': 'Female'
    })
)

print(df['gender'].unique())                    #check the male female or Nan
df

[nan 'Male' 'Female']

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,consumer,Male,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,enterprise,Male,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,consumer,Male,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,smb,Male,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,smb,Female,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,smb,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,consumer,NaN,yes,No,2024-02-22,???,good

In [51]:
#13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
#No, no, N, 0 become 0.

df['is_active'] = (
    df['is_active']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'yes': 1,
        'y': 1,
        '1': 1,
        'no': 0,
        'n': 0,
        '0': 0
    })
)
df

df['is_active'].unique()
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,1,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,consumer,Male,nan,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,consumer,Male,1,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,enterprise,Male,0,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,consumer,Male,0,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,smb,Female,1,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,smb,NaN,0,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,consumer,NaN,1,No,2024-02-22,???,good

In [52]:
#14.Convert the churn_flag column from categorical values (Yes/No) into a binary
#numerical column (1/0).


# Convert churn_flag Yes/No to 1/0
df["churn_flag"] = df["churn_flag"].map({
    "Yes": 1,
    "No": 0
})

print(df["churn_flag"].head())

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: churn_flag, dtype: float64

In [55]:
#15.Identify all values in income_usd that cannot be directly interpreted as
#numbers.

# Convert income_usd to numeric
# Invalid values become NaN
income_numeric = pd.to_numeric(df["income_usd"], errors="coerce")

# Display values that cannot be interpreted as numbers
invalid_income = df.loc[
    income_numeric.isna() & df["income_usd"].notna(),
    "income_usd"
]

print(invalid_income)

5             $44,696
10            $41,941
32           $123,682
35            $40,978
48            $45,565
            ...
1921    not available
1939         $135,575
1953          $34,809
1968          $80,389
1980          $58,046
Name: income_usd, Length: 205, dtype: object

In [56]:
#16.Clean income_usd by removing currency symbols, commas, and invalid text,
#then convert it to a numeric column using pd.to_numeric().

# Remove currency symbols and commas
df["income_usd"] = (
    df["income_usd"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

# Convert invalid text to NaN and make the column numeric
df["income_usd"] = pd.to_numeric(df["income_usd"], errors="coerce")

print(df["income_usd"].head())
print(df["income_usd"].dtype)

0    28198.410334
1    61312.831291
2    44199.671239
3    56259.909611
4    31238.641956
Name: income_usd, dtype: float64
float64

In [57]:
#17.Clean the Age column so values such as "35 years" become numeric values.

# Remove "years" and convert Age to numeric
df["age"] = (
    df["age"]
    .astype(str)
    .str.replace("years", "", regex=False)
    .str.strip()
)

df["age"] = pd.to_numeric(df["age"], errors="coerce")

print(df["age"].head())
print(df["age"].dtype)

0    45.867417
1    47.765164
2          NaN
3    62.723578
4          NaN
Name: age, dtype: float64
float64

In [58]:
#18.Identify unrealistic age values using NumPy/Pandas and replace them with
#NaN.


import numpy as np

# Identify unrealistic age values
df.loc[(df["age"] < 18) | (df["age"] > 100), "age"] = np.nan

print(df["age"].head())

0    45.867417
1    47.765164
2          NaN
3    62.723578
4          NaN
Name: age, dtype: float64

In [60]:
print("Unrealistic age values:",
      df[(df["age"] < 18) | (df["age"] > 100)]["age"].tolist())

Unrealistic age values: []

In [64]:
#19.Clean the credit_score column by removing text such as "pts" and converting
#the column to numeric.

# Remove "pts" and convert credit_score to numeric
df["credit_score"] = (
    df["credit_score"]
    .astype(str)
    .str.replace("pts", "", regex=False)
    .str.strip()
)

df["credit_score"] = pd.to_numeric(
    df["credit_score"],
    errors="coerce"
)
df["credit_score"].head()
df["credit_score"].dtype

dtype('float64')

In [65]:
#20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.

import numpy as np

# Calculate Q1 and Q3
Q1 = df["income_usd"].quantile(0.25)
Q3 = df["income_usd"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate lower and upper limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Find outliers
outliers = df[
    (df["income_usd"] < lower_limit) |
    (df["income_usd"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print("\nOutliers:")
print(outliers["income_usd"])

Q1: 38185.45685116151
Q3: 82369.30610169523
IQR: 44183.84925053372
Lower Limit: -28090.317024639065
Upper Limit: 148645.0799774958

Outliers:
65      248156.714139
101     204783.981770
116     785035.670283
137     211200.518666
141     159459.956802
            ...
1846    327022.958154
1852    795063.796842
1914    168194.079680
1918    234262.106128
1936    258343.545730
Name: income_usd, Length: 77, dtype: float64

In [68]:
#21.Detect outliers in credit_score using the IQR method.

# Calculate Q1 and Q3
Q1 = df["credit_score"].quantile(0.25)
Q3 = df["credit_score"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Find outliers
outliers = df[
    (df["credit_score"] < lower_limit) |
    (df["credit_score"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print("\nOutliers:")
print(outliers["credit_score"])

Q1: 588.5711718230643
Q3: 708.90454811873
IQR: 120.33337629566563
Lower Limit: 408.0711073795659
Upper Limit: 889.4046125622284

Outliers:
62      404.916112
348     395.344523
377     372.537221
422     162.336676
425     181.226520
446     141.922797
664     252.000000
705     218.521526
734     362.424198
793     211.984092
877     215.344839
904     389.270475
922     406.124323
942     240.729898
1024    195.707600
1027    151.039790
1102    216.621015
1194    225.420626
1263    393.470831
1425    356.305997
1516    280.213170
1613    248.101304
1630    261.433939
1665    179.409088
1830    332.371104
Name: credit_score, dtype: float64

In [71]:
#22.Detect suspicious values such as -999 and 99999 in tenure_years and
#satisfaction.

suspicious = df[
    df["tenure_years"].isin([-999, 99999]) |
    df["satisfaction"].isin([-999, 99999])
]

print(suspicious[["tenure_years", "satisfaction"]])

      tenure_years  satisfaction
29     -999.000000      3.391060
161   99999.000000      3.449143
358   99999.000000      2.956488
459       9.649929   -999.000000
533   99999.000000      3.083209
730       2.008998  99999.000000
788            NaN  99999.000000
894       1.206751   -999.000000
906    -999.000000      3.911122
948       3.683234  99999.000000
1136  99999.000000      3.640326
1165      5.782927  99999.000000
1421  99999.000000      3.601668
1499      2.083318   -999.000000
1627  99999.000000      5.000000
1652      4.345689   -999.000000
1657      3.909337  99999.000000
1728   -999.000000           NaN
1872      6.100963  99999.000000
1959   -999.000000      4.020120

In [72]:
#23.Replace invalid/suspicious numerical values with NaN.

import numpy as np

# Replace suspicious values with NaN
df["tenure_years"] = df["tenure_years"].replace([-999, 99999], np.nan)

df["satisfaction"] = df["satisfaction"].replace([-999, 99999], np.nan)

# Check again
print(df[["tenure_years", "satisfaction"]].head())

   tenure_years  satisfaction
0      5.274076      3.382150
1      5.632826           NaN
2           NaN      4.195157
3      2.029634           NaN
4      2.648626      3.117326

In [76]:
df["tenure_years"].isin([-999, 99999]).sum()
df["satisfaction"].isin([-999, 99999]).sum()

np.int64(0)

In [78]:
#24.Fill missing numerical values using the median of each numerical column.

# Select numerical columns
numeric_cols = df.select_dtypes(include=np.number).columns

# Fill missing values with column-wise median
df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)

# Check missing values
df[numeric_cols].isnull().sum()

age               0
income_usd        0
credit_score      0
tenure_years      0
monthly_visits    0
satisfaction      0
churn_flag        0
dtype: int64

In [81]:
#25.Fill missing categorical values using the mode of each categorical column.
# Select categorical columns
categorical_cols = df.select_dtypes(include="object").columns

# Fill missing categorical values with the mode of each column
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Check missing values
df[categorical_cols].isnull().sum()

customer_id         0
city                0
customer_segment    0
gender              0
is_active           0
signup_date         0
lead_source         0
notes_text          0
dtype: int64

In [85]:
#26.Clean the signup_date column, which contains multiple date formats and
#invalid dates, and convert it to Pandas datetime.

# Convert signup_date to datetime
df["signup_date"] = pd.to_datetime(
    df["signup_date"],
    errors="coerce"
)
df
# Check the result
df["signup_date"].head()
df["signup_date"].dtype
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,0.0,2026-03-11,Referral,normal
1,CUST-00354,47.765164,61312.831291,838.000000,5.632826,9.0,3.742125,Hyderabad,consumer,Male,nan,0.0,NaT,website,follow-up needed
2,CUST-01334,37.944404,44199.671239,613.132775,4.683845,8.0,4.195157,Mumbai,consumer,Male,1,0.0,2024-09-20,Email,normal
3,CUST-00906,62.723578,56259.909611,720.236986,2.029634,4.0,3.742125,Chennai,enterprise,Male,0,0.0,2023-07-12,Website,normal
4,CUST-01290,37.944404,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,0.0,2024-08-06,referral,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269512,79436.893353,633.974006,14.007477,6.0,3.556073,Bengaluru,consumer,Male,0,0.0,2024-02-26,email,normal
1996,CUST-01295,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,1.0,2024-08-11,Website,good
1997,CUST-00861,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb,Female,1,0.0,2023-05-27,WEB,???
1998,CUST-01460,42.300000,84103.610558,521.000000,7.168156,5.0,3.579652,Hyderabad,smb,Male,0,1.0,2025-01-26,Email,ok
1999,CUST-01127,59.256095,53723.873924,576.739073,9.720663,6.0,1.100520,Pune,consumer,Male,1,0.0,2024-02-22,???,good

In [86]:
#27.Find rows where signup_date could not be converted into a valid date.

# Find rows where signup_date is invalid
invalid_dates = df[df["signup_date"].isna()]

print(invalid_dates)

     customer_id        age    income_usd  credit_score  tenure_years  \
1     CUST-00354  47.765164  61312.831291    838.000000      5.632826
5     CUST-01274  37.944404  44696.000000    647.914390      1.700044
7     CUST-01732  37.630010  80888.862637    850.000000      4.489813
11    CUST-01293  37.944404  56124.711724    744.408134      6.966279
13    CUST-00585  37.944404  56124.711724    647.914390      2.786554
...          ...        ...           ...           ...           ...
1981  CUST-01688  40.975371  69577.953590    705.831623      4.683845
1982  CUST-00872  25.905285  37890.553580    674.000000      0.923243
1983  CUST-01124  35.170048  74269.078355    703.564221      4.683845
1986  CUST-01483  39.375013  94014.279803    563.745109      3.605231
1988  CUST-01239  45.400000  90683.095942    719.914379      7.362245

      monthly_visits  satisfaction       city customer_segment  gender  \
1                9.0      3.742125  Hyderabad         consumer    Male
5               12.0      3.742125  Bengaluru              smb    Male
7               11.0      3.742125       Pune         consumer  Female
11               1.0      3.990252  Bengaluru              smb  Female
13               8.0      3.742125     Mumbai              smb    Male
...              ...           ...        ...              ...     ...
1981             4.0      2.808807     Mumbai         consumer    Male
1982             8.0      3.427559    Chennai         consumer    Male
1983             7.0      3.486785       Pune              smb  Female
1986             7.0      3.726318      Delhi       enterprise  Female
1988             9.0      4.418195  Hyderabad       enterprise    Male

     is_active  churn_flag signup_date lead_source        notes_text
1          nan         0.0         NaT     website  follow-up needed
5            1         1.0         NaT   referral   follow-up needed
7            0         0.0         NaT   referral      good customer
11           1         0.0         NaT     Website               ???
13           1         0.0         NaT   referral                ???
...        ...         ...         ...         ...               ...
1981         0         1.0         NaT         ???            good
1982       nan         0.0         NaT       Email      complaint!!!
1983         0         0.0         NaT   referral             normal
1986         0         0.0         NaT   referral             normal
1988         1         0.0         NaT    Referral            good

[406 rows x 15 columns]

In [88]:
#28.Clean the lead_source column by standardizing values such as Website,
#website, WEB, Referral, referral , Google Ads, and google_ads.


#Clean and standardize lead_source
df["lead_source"] = (
    df["lead_source"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        "web": "website",
        "website": "website",
        "referral": "referral",
        "google_ads": "google ads",
        "google ads": "google ads"
    })
)

# Check unique values
df["lead_source"].unique()

array(['referral', 'website', 'email', 'google ads', 'social', 'unknown',
       '???'], dtype=object)

In [89]:
#29.Create a final cleaned DataFrame containing:
#• cleaned column names
#• no duplicate IDs
#• standardized categorical values
#• numeric columns converted to numeric types
#• invalid values converted to NaN
#• missing values handled
#• detected outliers handled


# Make a copy of the cleaned dataset
final_df = df.copy()

# 1. Clean column names
final_df.columns = (
    final_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 2. Remove duplicate Customer IDs
final_df = final_df.drop_duplicates(subset="customer_id")

# 3. Convert numeric columns to numeric
numeric_cols = [
    "age",
    "income_usd",
    "credit_score",
    "tenure_years",
    "monthly_visits",
    "satisfaction",
    "churn_flag"
]
for col in numeric_cols:
    final_df[col] = pd.to_numeric(final_df[col], errors="coerce")

# 4. Replace invalid/suspicious values with NaN
final_df["tenure_years"] = final_df["tenure_years"].replace([-999, 99999], np.nan)
final_df["satisfaction"] = final_df["satisfaction"].replace([-999, 99999], np.nan)

# 5. Fill numerical missing values with median
final_df[numeric_cols] = final_df[numeric_cols].fillna(
    final_df[numeric_cols].median()
)

# 6. Fill categorical missing values with mode
categorical_cols = final_df.select_dtypes(include="object").columns

for col in categorical_cols:
    final_df[col] = final_df[col].fillna(final_df[col].mode()[0])

# 7. Convert signup_date to datetime
final_df["signup_date"] = pd.to_datetime(
    final_df["signup_date"],
    errors="coerce"
)

# 8. Check final DataFrame
print(final_df.head())
print("\nShape:", final_df.shape)
print("\nData Types:")
print(final_df.dtypes)
print("\nMissing Values:")
print(final_df.isnull().sum())

  customer_id        age    income_usd  credit_score  tenure_years  \
0  CUST-01861  45.867417  28198.410334    660.562918      5.274076
1  CUST-00354  47.765164  61312.831291    838.000000      5.632826
2  CUST-01334  37.944404  44199.671239    613.132775      4.683845
3  CUST-00906  62.723578  56259.909611    720.236986      2.029634
4  CUST-01290  37.944404  31238.641956    549.183252      2.648626

   monthly_visits  satisfaction       city customer_segment gender is_active  \
0             5.0      3.382150       Pune         consumer   Male         1
1             9.0      3.742125  Hyderabad         consumer   Male       nan
2             8.0      4.195157     Mumbai         consumer   Male         1
3             4.0      3.742125    Chennai       enterprise   Male         0
4             5.0      3.117326     Mumbai       enterprise   Male         1

   churn_flag signup_date lead_source        notes_text
0         0.0  2026-03-11    referral            normal
1         0.0         NaT     website  follow-up needed
2         0.0  2024-09-20       email            normal
3         0.0  2023-07-12     website            normal
4         0.0  2024-08-06    referral               ???

Shape: (1980, 15)

Data Types:
customer_id                 object
age                        float64
income_usd                 float64
credit_score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
city                        object
customer_segment            object
gender                      object
is_active                   object
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object

Missing Values:
customer_id           0
age                   0
income_usd            0
credit_score          0
tenure_years          0
monthly_visits        0
satisfaction          0
city                  0
customer_segment      0
gender                0
is_active             0
churn_flag            0
signup_date         404
lead_source           0
notes_text            0
dtype: int64

In [90]:
#30.Perform a final data-quality audit using Pandas and NumPy:
#• Check remaining missing values
#• Check duplicate rows
#• Check duplicate customer IDs
#• Check data types
#• Check numerical ranges
#• Check unique categorical values
#• Confirm the final dataset is ready for analysis/ML


import pandas as pd
import numpy as np

# 1. Check remaining missing values
print("1. Missing Values:")
print(final_df.isnull().sum())

# 2. Check duplicate rows
print("\n2. Duplicate Rows:")
print("Duplicate rows:", final_df.duplicated().sum())

# 3. Check duplicate Customer IDs
print("\n3. Duplicate Customer IDs:")
print("Duplicate Customer IDs:",
      final_df["customer_id"].duplicated().sum())

# 4. Check data types
print("\n4. Data Types:")
print(final_df.dtypes)

# 5. Check numerical ranges
print("\n5. Numerical Ranges:")
print(final_df.select_dtypes(include=np.number).describe().T[
    ["min", "max"]
])

# 6. Check unique categorical values
print("\n6. Unique Categorical Values:")

categorical_cols = final_df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n{col}:")
    print(final_df[col].unique())

# 7. Final dataset information
print("\n7. Final Dataset Shape:")
print(final_df.shape)

print("\n8. Final Dataset Info:")
final_df.info()

1. Missing Values:
customer_id           0
age                   0
income_usd            0
credit_score          0
tenure_years          0
monthly_visits        0
satisfaction          0
city                  0
customer_segment      0
gender                0
is_active             0
churn_flag            0
signup_date         404
lead_source           0
notes_text            0
dtype: int64

2. Duplicate Rows:
Duplicate rows: 0

3. Duplicate Customer IDs:
Duplicate Customer IDs: 0

4. Data Types:
customer_id                 object
age                        float64
income_usd                 float64
credit_score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
city                        object
customer_segment            object
gender                      object
is_active                   object
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object

5. Numerical Ranges:
                         min           max
age                18.000000  9.974357e+01
income_usd      10198.638783  1.667567e+06
credit_score      141.922797  8.500000e+02
tenure_years        0.073142  2.000000e+01
monthly_visits      0.000000  8.000000e+01
satisfaction        1.000000  5.000000e+00
churn_flag          0.000000  1.000000e+00

6. Unique Categorical Values:

customer_id:
['CUST-01861' 'CUST-00354' 'CUST-01334' ... 'CUST-00861' 'CUST-01460'
 'CUST-01127']

city:
['Pune' 'Hyderabad' 'Mumbai' 'Chennai' 'Bengaluru' 'Kolkata' 'Delhi']

customer_segment:
['consumer' 'enterprise' 'smb' 'unknown']

gender:
['Male' 'Female']

is_active:
[1 'nan' 0]

lead_source:
['referral' 'website' 'email' 'google ads' 'social' 'unknown' '???']

notes_text:
['normal' 'follow-up needed' '???' 'good customer' 'complaint!!!' 'ok'
 'VIP' 'urgent' 'good  ' 'late payment']

7. Final Dataset Shape:
(1980, 15)

8. Final Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 1980 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1980 non-null   object
 1   age               1980 non-null   float64
 2   income_usd        1980 non-null   float64
 3   credit_score      1980 non-null   float64
 4   tenure_years      1980 non-null   float64
 5   monthly_visits    1980 non-null   float64
 6   satisfaction      1980 non-null   float64
 7   city              1980 non-null   object
 8   customer_segment  1980 non-null   object
 9   gender            1980 non-null   object
 10  is_active         1980 non-null   object
 11  churn_flag        1980 non-null   float64
 12  signup_date       1576 non-null   datetime64[ns]
 13  lead_source       1980 non-null   object
 14  notes_text        1980 non-null   object
dtypes: datetime64[ns](1), float64(7), object(7)
memory usage: 247.5+ KB